version: '3.7'

x-web-environment:
  &web-environment
  environment:
    - PORT=8000
    - ENVIRONMENT_NAME=test
    - USING_DOCKER_COMPOSE=true
    - DJANGO_SETTINGS_MODULE=config.settings.test
    - DJANGO_CONFIGURATION=Test
    - DJANGO_SECRET_KEY=nosecret
    - POSTGRES_PASSWORD=postgres
  build:
    context: ./
    dockerfile: Dockerfile.local
  volumes:
    - type: bind
      source: ./
      target: /code
  depends_on:
    - postgres
    - redis

services:
  postgres:
    image: postgres:alpine
    environment: 
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis:alpine

  web:
    <<: *web-environment
    restart: always
    image: web
    ports:
      - "8000:8000"
    command: scripts/local/run_web.sh
