# Generated by Django 3.0.3 on 2020-03-03 12:44

import api.advice.models.utils
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import model_utils.fields
from django.apps import apps
from django.core.management import call_command
import uuid


def run_tag_type_fixture(apps: apps, schema_editor):
    call_command("loaddata", "tagtypes")


def run_tag_fixture(apps: apps, schema_editor):
    call_command("loaddata", "tags")


class Migration(migrations.Migration):

    dependencies = [("advice", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="TagType",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        overwrite=True,
                        populate_from="title",
                        verbose_name="slug",
                    ),
                ),
            ],
            options={"verbose_name": "Tag type", "verbose_name_plural": "Tag types",},
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        overwrite=True,
                        populate_from="title",
                        verbose_name="slug",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        default=api.advice.models.utils.get_default_tag_type,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="advice.TagType",
                    ),
                ),
            ],
            options={"verbose_name": "tag", "verbose_name_plural": "tags",},
        ),
        migrations.CreateModel(
            name="Mapping",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "advice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="advice.Advice"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="advice.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "advice's tags",
                "verbose_name_plural": "advices' tags",
            },
        ),
        migrations.AddField(
            model_name="advice",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                through="advice.Mapping",
                to="advice.Tag",
                verbose_name="advice's tags",
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["title"], name="advice_tag_title_03fb61_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="tag", unique_together={("title", "slug")},
        ),
        migrations.AddIndex(
            model_name="mapping",
            index=models.Index(
                fields=["tag", "advice"], name="advice_mapp_tag_id_5ce929_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mapping", unique_together={("tag", "advice")},
        ),
        migrations.RunPython(run_tag_type_fixture),
        migrations.RunPython(run_tag_fixture),
    ]
