# Generated by Django 3.0.3 on 2020-02-27 10:01

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['title'], name='advice_tag_title_03fb61_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('title', 'slug')},
        ),
        migrations.AddField(
            model_name='advice',
            name='tags',
            field=models.ManyToManyField(to='advice.Tag', blank=True, verbose_name='advice tags'),
        ),
    ]
