# Generated by Django 3.0.3 on 2020-02-28 08:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'verbose_name': "advice's tags",
                'verbose_name_plural': "advices' tags",
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['title'], name='advice_tag_title_03fb61_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('title', 'slug')},
        ),
        migrations.AddField(
            model_name='mapping',
            name='advice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advice.Advice'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advice.Tag'),
        ),
        migrations.AddField(
            model_name='advice',
            name='tags',
            field=models.ManyToManyField(blank=True, through='advice.Mapping', to='advice.Tag', verbose_name="advice's tags"),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(fields=['tag', 'advice'], name='advice_mapp_tag_id_5ce929_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mapping',
            unique_together={('tag', 'advice')},
        ),
    ]
