# Generated by Django 3.0.3 on 2020-03-05 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advice", "0002_auto_20200303_1244"),
    ]

    operations = [
        migrations.AddField(
            model_name="advice",
            name="score",
            field=models.DecimalField(
                decimal_places=3,
                default=0.0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(10.0),
                ],
                verbose_name="the advice score among users who left a comment",
            ),
        ),
    ]
